version: '3'
services:
  webserver:
    image: aminetry1test.azurecr.io/aminetry1test:a
    ports:
      - "80:80"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    
