name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build Docker image
      run: docker build -t my-nginx-image .

    - name: Tag Docker image
      run: docker tag my-nginx-image aminetry1test.azurecr.io/my-nginx-image:latest

    - name: Push Docker image to ACR
      run: docker push aminetry1test.azurecr.io/my-nginx-image:latest

    - name: Deploy to Azure Web App
      run: az webapp config container set --name my-webapp --resource-group aminetry1test --docker-custom-image-name aminetry1test.azurecr.io/my-nginx-image:latest
